### ISSUE TITLE
panics when robots_txt is not valid

### ISSUE THREAD

**Issue by iyzana** [Folyd/robotstxt#2]
Fetching `https://install.pivpn.io/robots.txt` redirects to `https://raw.githubusercontent.com/pivpn/pivpn/master/auto_install/install.sh` which is a `text/plain` shell script.

The parser panics when trying to parse that file.
```
thread 'main' panicked at 'assertion failed: self.type_ == ParseKeyType::Unknown && !self.key_text.is_empty()', /home/me/.local/share/cargo/git/checkouts/robotstxt-269483cb38f6894f/ffe972d/src/parser.rs:88:9
```

I'm not entirely sure what the correct behavior should be, but simply ignoring unparsable lines seems like a good option.

**Comment by Folyd** [comment]
This has been fixed too. See commit above. Thanks a lot. 👍

**Comment by dkvasnicka** [comment]
@Folyd would you consider using `Result` as a return value from the top-level methods in your API to be in line with Rust standards and rustacean best practices, so that a parsing error does not crash the entire application that is using this library? I found another case where invalid robots.txt file causes a panic. If your API was returning a `Result` it would be a lot easier for us users of the library to work around inevitable bugs like these. The current approach does not scale.
